# Financiamiento público ajustado a la inflación a precios corrientes:

## Cargamos las Librerías:

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns
import janitor
import numpy as np
import pandas as pd
import session_info
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.float_format', '{:.2f}'.format)

## Generamos lod Datos de Inflación:

In [4]:
promedio_inpc_anual = {
    1997: 31.41, 1998: 36.41, 1999: 42.45, 2000: 46.48, 2001: 49.43,
    2002: 51.92, 2003: 54.28, 2004: 56.83, 2005: 59.09, 2006: 61.24,
    2007: 63.67, 2008: 66.93, 2009: 70.48, 2010: 73.41, 2011: 75.91,
    2012: 79.03, 2013: 82.04, 2014: 85.33, 2015: 87.65, 2016: 90.13,
    2017: 95.57, 2018: 100.26, 2019: 103.90, 2020: 107.43, 2021: 113.54,
    2022: 122.51, 2023: 129.28
}

## Creamos los Datos de Financiamiento:

In [5]:
financiamiento_original = {
    1997: 2446723214.77, 1998: 1046566954.67, 1999: 1312364397.62, 2000: 3064092232.97,
    2001: 2250685592.84, 2002: 2439871186.19, 2003: 4942596068.79, 2004: 1854015953.66,
    2005: 2013252441.28, 2006: 4171096908.42, 2007: 2704100762.62, 2008: 2690311483.58,
    2009: 3631639027.92, 2010: 2997358834.02, 2011: 3212932808.88, 2012: 5142514887.61,
    2013: 3670843752.88, 2014: 4002018895.98, 2015: 5122198499.05, 2016: 4031121882.70,
    2017: 4138727087.00, 2018: 6745554160.00, 2019: 4965828351.00, 2020: 5239001651.00,
    2021: 6871356602.00, 2022: 5821851702.00, 2023: 6233510798.00
}

## Creamos Listas para Almacenar los Datos:

In [6]:
anios = []
tasas_inflacion = []
financiamiento_publico_original = []
financiamiento_con_inflacion = []

## Iteramos para Generar los Resultados:

In [7]:
for año in range(1998, 2024):  # Comienza en 1998 para comparar con 1997 y avanza hasta 2023
    inflacion_anual = ((promedio_inpc_anual[año] - promedio_inpc_anual[año - 1]) / promedio_inpc_anual[año - 1]) * 100
    financiamiento_estimado = financiamiento_original[año - 1] * (1 + inflacion_anual / 100)

    # Almacenar datos en las listas
    anios.append(año)
    tasas_inflacion.append(inflacion_anual)
    financiamiento_publico_original.append(financiamiento_original[año])
    financiamiento_con_inflacion.append(financiamiento_estimado)

## Creamos el Dataframe:

In [8]:
df_comparativo = pd.DataFrame({
    "Año": anios,
    "Inflación (%)": tasas_inflacion,
    "Financiamiento Público Original": financiamiento_publico_original,
    "Financiamiento con Inflación": financiamiento_con_inflacion
})

## Visualizamos los Resultados:

In [12]:
df_comparativo

,Año,Inflación (%),Financiamiento Público Original,Financiamiento con Inflación
0,1998,15.92,1046566954.67,2836204783.50
1,1999,16.59,1312364397.62,1220180368.74
2,2000,9.49,3064092232.97,1436953997.68
3,2001,6.35,2250685592.84,3258564524.00
4,2002,5.04,2439871186.19,2364062229.02
5,2003,4.55,4942596068.79,2550774421.93
6,2004,4.70,1854015953.66,5174792457.43
7,2005,3.98,2013252441.28,1927745956.39
8,2006,3.64,4171096908.42,2086504983.99
9,2007,3.97,2704100762.62,4336605815.79
10,2008,5.12,2690311483.58,2842554798.84
11,2009,5.30,3631639027.92,2833006923.09
12,2010,4.16,2997358834.02,3782613805.90
13,2011,3.41,3212932808.88,3099434805.75
14,2012,4.11,5142514887.61,3344988537.55
15,2013,3.81,3670843752.88,5338376836.39
16,2014,4.01,4002018895.98,3818053357.30
17,2015,2.72,5122198499.05,4110828035.07
18,2016,2.83,4031121882.70,5267127789.15
19,2017,6.04,4138727087.00,4274429361.25
20,2018,4.91,6745554160.00,4341830885.66
21,2019,3.63,4965828351.00,6990455587.71
22,2020,3.40,5239001651.00,5134542249.74
23,2021,5.69,6871356602.00,5536965907.61
24,2022,7.90,5821851702.00,7414214350.11
25,2023,5.53,6233510798.00,6143571855.64